"""
handlers/recon.py — /recon <domain>: runs the full passive recon pipeline
in one command, sending results progressively as separate messages.
/report <domain>: runs the same pipeline (plus a few extra checks) and
sends back a single downloadable Markdown report instead — the "turn
findings into a deliverable" step real pentest/bug-bounty work needs.

Both are genuinely just automation, not new capability: they call the
exact same get_*_text() functions that /whois, /dns, /subdomains,
/headers, /audit, /techstack, /robots, and /securitytxt already use
individually — nothing here re-implements any lookup logic. Each
function already catches its own errors and returns a message string
instead of raising, so one slow/failing check can't block the others.
"""

import io
from datetime import datetime, timezone
from core import bot
from formatting import safe_reply
from .osint import get_whois_text, get_dns_text, get_subdomains_text, get_headers_text
from .security import get_audit_text
from .bugbounty import get_techstack_text, get_robots_text, get_securitytxt_text


def _build_steps(domain):
    return [
        ("📄 WHOIS", "WHOIS", lambda: get_whois_text(domain)),
        ("🌐 DNS Records", "DNS Records", lambda: get_dns_text(domain)),
        ("🔎 Subdomains", "Subdomains", lambda: get_subdomains_text(domain)),
        ("📡 Headers", "HTTP Headers", lambda: get_headers_text(domain)),
        ("🔧 Tech Stack", "Tech Stack", lambda: get_techstack_text(domain)),
        ("🛡 Security Audit", "Security Audit", lambda: get_audit_text(domain)),
        ("🤖 robots.txt", "robots.txt", lambda: get_robots_text(domain)),
        ("🔐 security.txt", "security.txt", lambda: get_securitytxt_text(domain)),
    ]


@bot.message_handler(commands=["recon"])
def recon_cmd(message):
    domain = message.text.replace("/recon", "", 1).strip()
    if not domain:
        bot.reply_to(
            message,
            "Usage: /recon <domain>\ne.g. /recon example.com\n\n"
            "Runs WHOIS, DNS, subdomains, headers, tech stack, security audit, "
            "robots.txt, and security.txt in one go — all automated.\n\n"
            "⚠️ Use only on targets you own or have explicit permission to test.",
        )
        return

    bot.reply_to(message, f"🔎 Starting recon on *{domain}*...", parse_mode="Markdown")

    for label, _, step_func in _build_steps(domain):
        bot.send_chat_action(message.chat.id, "typing")
        try:
            result = step_func()
        except Exception as e:
            result = f"⚠️ {label} step failed unexpectedly: {e}"
        safe_reply(message, result)

    bot.send_message(message.chat.id, f"✅ Recon complete for *{domain}*", parse_mode="Markdown")


def build_report(domain: str):
    """Runs the full pipeline and returns (filename, markdown_text) — kept
    separate from the Telegram-sending logic so it's testable on its own."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [f"# Recon Report: {domain}", f"_Generated by PyPal on {timestamp}_", "", "---", ""]
    for _, section_title, step_func in _build_steps(domain):
        try:
            content = step_func()
        except Exception as e:
            content = f"⚠️ This step failed unexpectedly: {e}"
        lines.append(f"## {section_title}\n")
        lines.append(content)
        lines.append("\n---\n")
    filename = f"recon_report_{domain.replace('.', '_').replace('/', '_')}.md"
    return filename, "\n".join(lines)


@bot.message_handler(commands=["report"])
def report_cmd(message):
    domain = message.text.replace("/report", "", 1).strip()
    if not domain:
        bot.reply_to(
            message,
            "Usage: /report <domain>\ne.g. /report example.com\n\n"
            "Runs the full recon pipeline and sends back a downloadable "
            "Markdown report instead of separate messages.\n\n"
            "⚠️ Use only on targets you own or have explicit permission to test.",
        )
        return
    bot.reply_to(
        message,
        f"📝 Generating report for *{domain}*... this runs the full pipeline, give it a moment.",
        parse_mode="Markdown",
    )
    bot.send_chat_action(message.chat.id, "upload_document")

    filename, report_text = build_report(domain)
    file_obj = io.BytesIO(report_text.encode("utf-8"))
    file_obj.name = filename
    bot.send_document(
        message.chat.id,
        file_obj,
        visible_file_name=filename,
        caption=f"✅ Report ready for {domain}",
    )
